'use client';

import React, { useMemo } from 'react';
import { format, parseISO, isValid } from 'date-fns';
import {
  Calendar,
  Clock,
  User,
  CheckCircle2,
  AlertTriangle,
  RotateCw,
  Home,
  TrendingUp,
  FileText,
  ShieldCheck,
  FileCheck2,
  Wrench,
  UserCheck,
  CheckSquare,
  MessageSquare,
  ChevronRight,
  Sparkles,
} from 'lucide-react';
import { ColDef, ICellRendererParams } from 'ag-grid-community';
import { AdminDataGrid } from '@/components/admin/data-grid/AdminDataGrid';
import { cn } from '@/lib/utils';
import type { ActivityBoardItem } from '@/types/activity';

export interface ActivityListProps {
  items: ActivityBoardItem[];
  onCardClick: (item: ActivityBoardItem) => void;
  onCompleteClick: (item: ActivityBoardItem) => void;
  onArchiveClick: (item: ActivityBoardItem) => void;
}

const TYPE_ICONS: Record<string, React.ElementType> = {
  inspection: Home,
  rent_review: TrendingUp,
  lease_expiry: FileText,
  insurance_renewal: ShieldCheck,
  lease_renewal: FileCheck2,
  repair: Wrench,
  maintenance: Wrench,
  tenant_issue: UserCheck,
  other: CheckSquare,
};

export function ActivityList({
  items,
  onCardClick,
  onCompleteClick,
  onArchiveClick,
}: ActivityListProps) {
  const columnDefs = useMemo<ColDef<ActivityBoardItem>[]>(() => {
    return [
      // 1. Activity Title & Indicators
      {
        field: 'title',
        headerName: 'Activity',
        minWidth: 280,
        flex: 2,
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item) return null;
          const isCompleted = item.status === 'completed';

          return (
            <div className="flex items-center gap-2 h-full py-1 min-w-0">
              <span
                className={cn(
                  'font-semibold text-xs text-foreground dark:text-white truncate',
                  isCompleted && 'line-through text-muted dark:text-slate-500'
                )}
                title={item.title}
              >
                {item.title}
              </span>

              {item.isAutoCreated && (
                <span
                  title={
                    item.autoSource
                      ? `Auto Created via ${item.autoSource}`
                      : 'Automatically generated by Autopilot'
                  }
                  className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-md text-[10px] font-bold bg-[#008F83]/10 text-[#008F83] dark:text-[#32D5C4] border border-[#008F83]/25 shrink-0"
                >
                  <Sparkles className="w-2.5 h-2.5" />
                  <span>Auto</span>
                </span>
              )}

              {item.isRecurring && (
                <span
                  title="Recurring Activity"
                  className="p-1 rounded bg-blue-500/10 text-blue-600 dark:text-blue-400 shrink-0"
                >
                  <RotateCw className="w-2.5 h-2.5" />
                </span>
              )}

              {item.commentCount > 0 && (
                <span
                  title={`${item.commentCount} comments`}
                  className="inline-flex items-center gap-0.5 text-[10px] text-muted dark:text-slate-400 shrink-0"
                >
                  <MessageSquare className="w-2.5 h-2.5" />
                  {item.commentCount}
                </span>
              )}
            </div>
          );
        },
      },

      // 2. Property
      {
        field: 'propertyName',
        headerName: 'Property',
        minWidth: 200,
        flex: 1.5,
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item) return null;

          return (
            <div className="flex items-center gap-1.5 h-full text-xs text-muted dark:text-slate-400 font-medium truncate">
              <Home className="w-3.5 h-3.5 text-slate-400 shrink-0" />
              <span className="truncate" title={item.propertyName || 'Unassigned Property'}>
                {item.propertyName || '—'}
              </span>
            </div>
          );
        },
      },

      // 3. Type
      {
        field: 'activityTypeName',
        headerName: 'Type',
        minWidth: 160,
        flex: 1,
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item) return null;
          const Icon = TYPE_ICONS[item.activityTypeId] || CheckSquare;

          return (
            <div className="flex items-center gap-1.5 h-full text-xs font-medium text-foreground dark:text-slate-200">
              <Icon className="w-3.5 h-3.5 text-[#008F83] dark:text-[#32D5C4] shrink-0" />
              <span className="truncate">{item.activityTypeName || 'Activity'}</span>
            </div>
          );
        },
      },

      // 4. Due Date
      {
        field: 'dueDate',
        headerName: 'Due Date',
        minWidth: 130,
        flex: 1,
        comparator: (d1: string, d2: string) => {
          if (!d1) return -1;
          if (!d2) return 1;
          return new Date(d1).getTime() - new Date(d2).getTime();
        },
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item?.dueDate) return <span className="text-muted text-xs">—</span>;

          try {
            const parsed = parseISO(item.dueDate);
            if (!isValid(parsed)) return <span className="text-muted text-xs">—</span>;
            return (
              <span className="text-xs font-medium text-foreground dark:text-slate-200 whitespace-nowrap">
                {format(parsed, 'dd MMM yyyy')}
              </span>
            );
          } catch {
            return <span className="text-muted text-xs">—</span>;
          }
        },
      },

      // 5. Responsible / Assignee
      {
        field: 'assignedToName',
        headerName: 'Responsible',
        minWidth: 160,
        flex: 1,
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item) return null;

          return (
            <div className="flex items-center gap-2 h-full text-xs">
              {item.assignedToName ? (
                <div className="flex items-center justify-center w-5 h-5 rounded-full bg-[#008F83]/15 text-[#008F83] dark:text-[#32D5C4] border border-[#008F83]/30 text-[10px] font-bold uppercase shrink-0">
                  {item.assignedToName.charAt(0)}
                </div>
              ) : (
                <div className="flex items-center justify-center w-5 h-5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-400 text-[10px] shrink-0">
                  <User className="w-3 h-3" />
                </div>
              )}
              <span className="truncate font-medium text-foreground dark:text-slate-300">
                {item.assignedToName || 'Unassigned'}
              </span>
            </div>
          );
        },
      },

      // 6. Status Badge
      {
        field: 'status',
        headerName: 'Status',
        minWidth: 140,
        flex: 1,
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item) return null;

          if (item.status === 'completed') {
            return (
              <div className="flex items-center h-full">
                <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
                  <CheckCircle2 className="w-3 h-3" />
                  Completed
                </span>
              </div>
            );
          }

          if (item.status === 'in_progress') {
            return (
              <div className="flex items-center h-full">
                <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20">
                  In Progress
                </span>
              </div>
            );
          }

          if (item.isOverdue) {
            return (
              <div className="flex items-center h-full">
                <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20">
                  <AlertTriangle className="w-3 h-3" />
                  {item.daysOverdue}d Overdue
                </span>
              </div>
            );
          }

          return (
            <div className="flex items-center h-full">
              <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">
                Due
              </span>
            </div>
          );
        },
      },

      // 7. Actions Column
      {
        colId: 'actions',
        headerName: 'Actions',
        width: 140,
        minWidth: 130,
        sortable: false,
        filter: false,
        pinned: 'right',
        cellRenderer: (params: ICellRendererParams<ActivityBoardItem>) => {
          const item = params.data;
          if (!item) return null;
          const isCompleted = item.status === 'completed';

          return (
            <div
              className="flex items-center justify-end gap-1.5 h-full"
              onClick={(e) => e.stopPropagation()}
            >
              {!isCompleted && (
                <button
                  type="button"
                  onClick={() => onCompleteClick(item)}
                  className="px-2.5 py-1 rounded-md text-[11px] font-semibold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-500/20 border border-emerald-500/20 transition-colors"
                >
                  Complete
                </button>
              )}
              <button
                type="button"
                onClick={() => onCardClick(item)}
                className="p-1 rounded-md text-muted hover:text-foreground dark:text-slate-400 dark:hover:text-white transition-colors"
                title="View details"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          );
        },
      },
    ];
  }, [onCardClick, onCompleteClick]);

  return (
    <div className="w-full flex flex-col bg-surface dark:bg-[#0B1320] border border-border dark:border-[#1E293B] rounded-2xl shadow-xs overflow-hidden">
      <AdminDataGrid<ActivityBoardItem>
        rowData={items}
        columnDefs={columnDefs}
        getRowId={(p) => p.data.id}
        onRowClick={(item) => onCardClick(item)}
        searchPlaceholder="Search activities by title, property, or assignee..."
        exportFilename="activities-list-export"
        enableExport={true}
        enableColumnChooser={true}
        enableSelection={false}
        labelSingular="activity"
        labelPlural="activities"
        emptyTitle="No activities found"
        emptyDescription="No activities match your current search and filters."
        defaultPageSize={15}
        rowHeight={52}
      />
    </div>
  );
}
