import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: "var(--surface)",
        "surface-elevated": "var(--surface-elevated)",
        "surface-subtle": "var(--surface-subtle)",
        muted: "var(--muted)",
        "muted-dark": "var(--muted-dark)",
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          subtle: "var(--accent-subtle)",
        },
        border: "var(--border)",
        "border-subtle": "var(--border-subtle)",
        "border-strong": "var(--border-strong)",
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
        info: "var(--info)",
        admin: {
          background: "var(--admin-background)",
          shell: "var(--admin-shell)",
          sidebar: "var(--admin-sidebar)",
          "sidebar-surface": "var(--admin-sidebar-surface)",
          "sidebar-border": "var(--admin-sidebar-border)",
          "sidebar-border-subtle": "var(--admin-sidebar-border-subtle)",
          "sidebar-foreground": "var(--admin-sidebar-foreground)",
          "sidebar-muted": "var(--admin-sidebar-muted)",
          "sidebar-hover": "var(--admin-sidebar-hover)",
          "sidebar-active-pill": "var(--admin-sidebar-active-pill)",
          "sidebar-active-pill-border": "var(--admin-sidebar-active-pill-border)",
          "sidebar-active-text": "var(--admin-sidebar-active-text)",
          surface: "var(--admin-surface)",
          "surface-elevated": "var(--admin-surface-elevated)",
          "surface-subtle": "var(--admin-surface-subtle)",
          border: "var(--admin-border)",
          "border-subtle": "var(--admin-border-subtle)",
          divider: "var(--admin-divider)",
          primary: "var(--admin-primary)",
          "primary-hover": "var(--admin-primary-hover)",
          "primary-soft": "var(--admin-primary-soft)",
          success: "var(--admin-success)",
          "success-soft": "var(--admin-success-soft)",
          warning: "var(--admin-warning)",
          "warning-soft": "var(--admin-warning-soft)",
          danger: "var(--admin-danger)",
          "danger-soft": "var(--admin-danger-soft)",
          info: "var(--admin-info)",
          "info-soft": "var(--admin-info-soft)",
          foreground: "var(--admin-foreground)",
          muted: "var(--admin-muted)",
          "muted-foreground": "var(--admin-muted-foreground)",
        },
      },
      fontFamily: {
        sans: ["var(--font-outfit)", "sans-serif"],
        heading: ["var(--font-space-grotesk)", "sans-serif"],
      },
      fontSize: {
        "display": ["40px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "page-title": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "section-title": ["22px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "card-title": ["17px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "body": ["15px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "caption": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "metadata": ["12px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
      },
      spacing: {
        "0.5": "2px",
        "1": "4px",
        "1.5": "6px",
        "2": "8px",
        "2.5": "10px",
        "3": "12px",
        "3.5": "14px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "7": "28px",
        "8": "32px",
        "9": "36px",
        "10": "40px",
        "11": "44px",
        "12": "48px",
        "14": "56px",
        "16": "64px",
        "20": "80px",
      },
      borderRadius: {
        sm: "8px",
        md: "10px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
        full: "9999px",
      },
      boxShadow: {
        "elevation-0": "none",
        "elevation-1": "0 1px 2px 0 var(--shadow-color), 0 1px 3px 0 var(--shadow-color)",
        "elevation-2": "0 4px 12px -2px var(--shadow-color), 0 2px 4px -2px var(--shadow-color)",
        "elevation-3": "0 12px 32px -8px var(--shadow-color), 0 4px 8px -4px var(--shadow-color)",
        "elevation-overlay": "0 24px 64px -16px var(--shadow-color), 0 8px 16px -8px var(--shadow-color)",
        "subtle-card": "0 20px 60px -15px var(--shadow-color)",
        "mockup": "0 25px 80px -20px var(--shadow-color), 0 0 0 1px var(--border)",
        "mockup-sm": "0 10px 30px -10px var(--shadow-color), 0 0 0 1px var(--border)",
      },
      transitionDuration: {
        "120": "120ms",
        "200": "200ms",
        "250": "250ms",
      },
      transitionTimingFunction: {
        "ease-out-quart": "cubic-bezier(0.25, 1, 0.5, 1)",
      },
      zIndex: {
        "dropdown": "1000",
        "sticky": "1020",
        "fixed": "1030",
        "modal-backdrop": "1040",
        "modal": "1050",
        "popover": "1060",
        "tooltip": "1070",
        "toast": "1080",
      },
    },
  },
  plugins: [],
};
export default config;